# According to
# https://docs.travis-ci.com/user/languages/minimal-and-generic/#generic, the
# generic language includes Go.
language: generic
os:
  - osx
  - bionic
compiler: clang

addons:
  apt:
    packages:
      # We need Python 3 for pre-commit checks.
      - python3-pip

install:
  - pip install pre-commit

env:
  global:
  - GOPATH=$HOME/go
  - PATH=$GOPATH/bin:$PATH

cache:
  directories:
    # https://pre-commit.com/#travis-ci-example
    - $HOME/.cache/pre-commit

branches:
  only:
    - master

before_install:
  - bash .scripts/install-ci-tools.sh

script:

  - (cd cgotorch; make)
  - pre-commit run -a
  - go run 01-backward.go
