# According to
# https://docs.travis-ci.com/user/languages/minimal-and-generic/#generic, the
# generic language includes Go.
language: generic
dist: osx

cache:
  directories:
    - cgotorch/libtorch

before_install:
  - sudo apt-get update
  - sudo apt-get install -y make wget clang

script:
  - (cd cgotorch; make)
  - go run 01-backward.go
